apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-tags-deployment
  labels: 
    app: so-tags
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: so-tags
  template:
    metadata:
      labels:
        app: so-tags
    spec: 
      containers: 
      - name: so-tags
        image: ghcr.io/sarajuhosova/so-tags:latest
        ports: 
        - containerPort: 8080

--- 
apiVersion: v1
kind: Service
metadata:
  name: so-tags-service
spec:
  selector: 
    app: so-tags
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 1234
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service:
      name: so-tags-service
      port:
        number: 1234
          
